### ISSUE TITLE
Setting an image as default does not work

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#399] opened 2016-06-28 23:42 UTC
Press the Heart button to set an image as default does not work.
The icon does not change either.

Have tested against posters, fanart and wide banners

![image](https://cloud.githubusercontent.com/assets/6645153/16436006/b788dc08-3ddd-11e6-9d7d-12980ffd7b11.png)

**Comment by hidden4003** [comment] 2016-07-12 20:05
I looked into this, the problem is on the server:
https://github.com/japanesemediamanager/jmmserver/blob/master/JMMServer/JMMServiceImplementation.cs#L1764
`AniDB_Anime anime = repAnime.GetByAnimeID(session, animeID);`
does not populate default poster

**Comment by ElementalCrisis** [comment] 2016-07-12 21:33
So you can get it to work doing the following.

![jmmdesktop_2016-07-12_14-33-12](https://cloud.githubusercontent.com/assets/9443295/16784423/a5f44918-483d-11e6-9f07-4590feebcb83.png)

In JMM Desktop:
1. Click the image you want as default. 
2. On the Series Info panel click "Update AniDB Data"

Doing this causes the images to be marked as default. 

![jmmdesktop_2016-07-12_14-33-31](https://cloud.githubusercontent.com/assets/9443295/16784432/ab1c412a-483d-11e6-8dce-084cdd04f459.png)

**Comment by hidden4003** [comment] 2016-07-13 05:34
And if you restart JMM Desktop it will be gone.

SO you are suggesting that the call that is used when "Update AniDB Data" should be used and not the GetAnime API call that is used now? It might make it slower, besides as far as I understand "Update AniDB Data" actually gets stuff from AniDB.

**Comment by ElementalCrisis** [comment] 2016-07-13 05:37
Oh no I was just pointing that out.

**Comment by hidden4003** [comment] 2016-07-13 07:02
I found 2 issues so far, one in the server [pull request link](https://github.com/japanesemediamanager/jmmserver/pull/309)

The other one is in the client, the default poster in the series gets corrupted somehow during the update, not to mention there are ~5 calls to GetAnime() on server all getting the same info, so I guess the update part has to be heavily reworked. I didn't figure out yet why and where the corruption occurs, might have something to do with threads, as some of the requests fire as a response to OnPropertyChanged.

**Comment by ElementalCrisis** [comment] 2016-07-13 07:05
I approved your pull request, thanks for the fix! :) 

Is the issue you described part of the reason we have to restart Desktop and Server for the image to be marked as default?

**Comment by hidden4003** [comment] 2016-07-13 07:11
There is no problem with the image being marked as default in the database, it is the caching and something else preventing you to see the change in the client.

I've only fixed the server part, which caused server not to update the contract, i.e. server would keep serving old default image but that is only an issue for AniDB poster being used as default, the other ones go as cross-refs so they are not getting cached in the Anime contract.

So yeah this probably fixes the restart part.

**Comment by ElementalCrisis** [comment] 2016-07-13 07:18
It does, just need to hit Update AniDB Data to get the client to show the image marked as default.

**Comment by hidden4003** [comment] 2016-07-13 07:21
The way anime details are now updated corrupts posters I will look into that but I don't have a lot of experience with WPF yet so I am not sure if I will be able to fix it.

**Comment by hidden4003** [comment] 2016-07-13 21:32
I was wrong, what I was thinking of as a corruption was actually a series contract served from cache.

**Comment by ElementalCrisis** [comment] 2016-07-14 04:55
Fixed in 3.6.0.1

https://github.com/japanesemediamanager/jmmserver/commit/757ba0968fb40bb5383bc029706ed6b23a6fbbdb

**Closed by ElementalCrisis** 2016-07-14 04:55 UTC
Labels: Bug - High Priority
