### ISSUE TITLE
JMM Desktop crashes when you search on MAL

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#35] opened 2014-08-19 06:58 UTC
**Reported by werndlymob, Jan 9, 2013**

The following error happens when scroll through too quickly, or search again when the results are still rendering

```
(Outer Exception)
Date and Time:         1/10/2013 1:59:28 PM
Machine Name:          DEV23
IP Address:            192.168.153.74
Current User:          PROJECTGOTH\lwerndly

Application Domain:    JMMDesktop.exe
Assembly Codebase:     file:///C:/Projects/SVN/JMM/trunk/JMMClient/JMMClient/bin/Debug/JMMDesktop.exe
Assembly Full Name:    JMMDesktop, Version=3.1.28.0, Culture=neutral, PublicKeyToken=c59d437d72a058a3
Assembly Version:      3.1.28.0
Assembly Build Date:   1/10/2013 10:31:17 AM

Exception Source:      PresentationFramework
Exception Type:        System.InvalidOperationException
Exception Message:     An ItemsControl is inconsistent with its items source.
  See the inner exception for more information.
Exception Target Site: Verify

---- Stack Trace ----
   System.Windows.Controls.ItemContainerGenerator.Verify()
       JMMDesktop.exe: N 02221
   System.Windows.Controls.VirtualizingStackPanel.MeasureChild(generator As IItemContainerGenerator&, itemStorageProvider As IContainItemStorage&, parentItem As Object&, hasUniformOrAverageContainerSizeBeenSet As Boolean&, computedUniformOrAverageContainerSize As Double&, computedAreContainersUniformlySized As Boolean&, items As IList&, item As Object&, children As IList&, childIndex As Int32&, visualOrderChanged As Boolean&, isHorizontal As Boolean&, childConstraint As Size&, viewport As Rect&, cacheSize As VirtualizationCacheLength&, cacheUnit As VirtualizationCacheLengthUnit&, foundFirstItemInViewport As Boolean&, firstItemInViewportOffset As Double&, stackPixelSize As Size&, stackPixelSizeInViewport As Size&, stackPixelSizeInCacheBeforeViewport As Size&, stackPixelSizeInCacheAfterViewport As Size&, stackLogicalSize As Size&, stackLogicalSizeInViewport As Size&, stackLogicalSizeInCacheBeforeViewport As Size&, stackLogicalSizeInCacheAfterViewport As Size&, mustDisableVirtualization As Boolean&, isBeforeFirstItem As Boolean, isAfterFirstItem As Boolean, isAfterLastItem As Boolean, skipActualMeasure As Boolean, skipGeneration As Boolean, hasBringIntoViewContainerBeenMeasured As Boolean&, hasVirtualizingChildren As Boolean&)
       JMMDesktop.exe: N 16664913
   System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(constraint As Size, lastPageSafeOffset As Nullable`1, previouslyMeasuredOffsets As List`1&, remeasure As Boolean)
       JMMDesktop.exe: N 04110
   System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(constraint As Size)
       JMMDesktop.exe: N 00151
   System.Windows.FrameworkElement.MeasureCore(availableSize As Size)
       JMMDesktop.exe: N 00787
   System.Windows.UIElement.Measure(availableSize As Size)
       JMMDesktop.exe: N 01313
   System.Windows.ContextLayoutManager.UpdateLayout()
       JMMDesktop.exe: N 01385
   System.Windows.Controls.<>c__DisplayClassb.<InitializeViewport>b__7()
       JMMDesktop.exe: N 00182
   System.Windows.Threading.ExceptionWrapper.InternalRealCall(callback As Delegate, args As Object, numArgs As Int32)
       JMMDesktop.exe: N 00380
   MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(source As Object, method As Delegate, args As Object, numArgs As Int32, catchHandler As Delegate)
       JMMDesktop.exe: N 00071
   System.Windows.Threading.DispatcherOperation.InvokeImpl()
       JMMDesktop.exe: N 00641
   System.Threading.ExecutionContext.RunInternal(executionContext As ExecutionContext, callback As ContextCallback, state As Object, preserveSyncCtx As Boolean)
       JMMDesktop.exe: N 00645
   System.Threading.ExecutionContext.Run(executionContext As ExecutionContext, callback As ContextCallback, state As Object, preserveSyncCtx As Boolean)
       JMMDesktop.exe: N 00009
   System.Threading.ExecutionContext.Run(executionContext As ExecutionContext, callback As ContextCallback, state As Object)
       JMMDesktop.exe: N 00087
   System.Windows.Threading.DispatcherOperation.Invoke()
       JMMDesktop.exe: N 00113
   System.Windows.Threading.Dispatcher.ProcessQueue()
       JMMDesktop.exe: N 00673
   System.Windows.Threading.Dispatcher.WndProcHook(hwnd As IntPtr, msg As Int32, wParam As IntPtr, lParam As IntPtr, handled As Boolean&)
       JMMDesktop.exe: N 00179
   MS.Win32.HwndWrapper.WndProc(hwnd As IntPtr, msg As Int32, wParam As IntPtr, lParam As IntPtr, handled As Boolean&)
       JMMDesktop.exe: N 00330
   MS.Win32.HwndSubclass.DispatcherCallbackOperation(o As Object)
       JMMDesktop.exe: N 00128
   System.Windows.Threading.ExceptionWrapper.InternalRealCall(callback As Delegate, args As Object, numArgs As Int32)
       JMMDesktop.exe: N 00094
   MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(source As Object, method As Delegate, args As Object, numArgs As Int32, catchHandler As Delegate)
       JMMDesktop.exe: N 00071
   System.Windows.Threading.Dispatcher.LegacyInvokeImpl(priority As DispatcherPriority, timeout As TimeSpan, method As Delegate, args As Object, numArgs As Int32)
       JMMDesktop.exe: N 00700
   MS.Win32.HwndSubclass.SubclassWndProc(hwnd As IntPtr, msg As Int32, wParam As IntPtr, lParam As IntPtr)
       JMMDesktop.exe: N 00320
   System.Windows.Forms.SafeNativeMethods.MessageBox(hWnd As HandleRef, text As String, caption As String, type As Int32)
       JMMDesktop.exe: N 00000
   System.Windows.Forms.MessageBox.ShowCore(owner As IWin32Window, text As String, caption As String, buttons As MessageBoxButtons, icon As MessageBoxIcon, defaultButton As MessageBoxDefaultButton, options As MessageBoxOptions, showHelp As Boolean)
       JMMDesktop.exe: N 01098
   System.Windows.Forms.MessageBox.Show(text As String, caption As String, buttons As MessageBoxButtons, icon As MessageBoxIcon)
       JMMDesktop.exe: N 00052
   JMMClient.Utils.ShowErrorMessage(ex As Exception)
       Utils.cs: line 0183, col 04, IL 0007
   JMMClient.UserControls.TvDBAndOtherLinks.SearchMAL()
       TvDBAndOtherLinks.xaml.cs: line 0106, col 05, IL 0144
   JMMClient.UserControls.TvDBAndOtherLinks.btnSearchExistingMAL_Click(sender As Object, e As RoutedEventArgs)
       TvDBAndOtherLinks.xaml.cs: line 0079, col 04, IL 0007
   System.Windows.EventRoute.InvokeHandlersImpl(source As Object, args As RoutedEventArgs, reRaised As Boolean)
       JMMDesktop.exe: N 00624
   System.Windows.UIElement.RaiseEventImpl(sender As DependencyObject, args As RoutedEventArgs)
       JMMDesktop.exe: N 00334
   System.Windows.Controls.Button.OnClick()
       JMMDesktop.exe: N 00165
   System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(e As MouseButtonEventArgs)
       JMMDesktop.exe: N 00279
   System.Windows.RoutedEventArgs.InvokeHandler(handler As Delegate, target As Object)
       JMMDesktop.exe: N 00086
   System.Windows.EventRoute.InvokeHandlersImpl(source As Object, args As RoutedEventArgs, reRaised As Boolean)
       JMMDesktop.exe: N 00624
   System.Windows.UIElement.ReRaiseEventAs(sender As DependencyObject, args As RoutedEventArgs, newEvent As RoutedEvent)
       JMMDesktop.exe: N 00387
   System.Windows.RoutedEventArgs.InvokeHandler(handler As Delegate, target As Object)
       JMMDesktop.exe: N 00086
   System.Windows.EventRoute.InvokeHandlersImpl(source As Object, args As RoutedEventArgs, reRaised As Boolean)
       JMMDesktop.exe: N 00624
   System.Windows.UIElement.RaiseEventImpl(sender As DependencyObject, args As RoutedEventArgs)
       JMMDesktop.exe: N 00334
   System.Windows.UIElement.RaiseTrustedEvent(args As RoutedEventArgs)
       JMMDesktop.exe: N 00100
   System.Windows.Input.InputManager.ProcessStagingArea()
       JMMDesktop.exe: N 01073
   System.Windows.Input.InputProviderSite.ReportInput(inputReport As InputReport)
       JMMDesktop.exe: N 00253
   System.Windows.Interop.HwndMouseInputProvider.ReportInput(hwnd As IntPtr, mode As InputMode, timestamp As Int32, actions As RawMouseActions, x As Int32, y As Int32, wheel As Int32)
       JMMDesktop.exe: N 01040
   System.Windows.Interop.HwndMouseInputProvider.FilterMessage(hwnd As IntPtr, msg As WindowMessage, wParam As IntPtr, lParam As IntPtr, handled As Boolean&)
       JMMDesktop.exe: N 00904
   System.Windows.Interop.HwndSource.InputFilterMessage(hwnd As IntPtr, msg As Int32, wParam As IntPtr, lParam As IntPtr, handled As Boolean&)
       JMMDesktop.exe: N 00124
   MS.Win32.HwndWrapper.WndProc(hwnd As IntPtr, msg As Int32, wParam As IntPtr, lParam As IntPtr, handled As Boolean&)
       JMMDesktop.exe: N 00330
   MS.Win32.HwndSubclass.DispatcherCallbackOperation(o As Object)
       JMMDesktop.exe: N 00128
   System.Windows.Threading.ExceptionWrapper.InternalRealCall(callback As Delegate, args As Object, numArgs As Int32)
       JMMDesktop.exe: N 00094
   MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(source As Object, method As Delegate, args As Object, numArgs As Int32, catchHandler As Delegate)
       JMMDesktop.exe: N 00071
   System.Windows.Threading.Dispatcher.LegacyInvokeImpl(priority As DispatcherPriority, timeout As TimeSpan, method As Delegate, args As Object, numArgs As Int32)
       JMMDesktop.exe: N 00700
   MS.Win32.HwndSubclass.SubclassWndProc(hwnd As IntPtr, msg As Int32, wParam As IntPtr, lParam As IntPtr)
       JMMDesktop.exe: N 00320
   MS.Win32.UnsafeNativeMethods.DispatchMessage(msg As MSG&)
       JMMDesktop.exe: N 00000
   System.Windows.Threading.Dispatcher.PushFrameImpl(frame As DispatcherFrame)
       JMMDesktop.exe: N 00274
   System.Windows.Application.RunInternal(window As Window)
       JMMDesktop.exe: N 00378
   System.Windows.Application.Run()
       JMMDesktop.exe: N 00103
   JMMClient.App.Main()
       App.g.cs: line 0000, col 00, IL 0014
```

**Comment by hidden4003** [comment] 2016-06-24 15:59
I am unable to reproduce this, the possible cause might be https://github.com/japanesemediamanager/jmmclient/blame/master/JMMClient/Forms/SearchMALForm.xaml.cs#L253

`foreach (JMMServerBinary.Contract_MALAnimeResponse malResult in malResults)
MALSearchResults.Add(new MALSearchResultVM(malResult));`

as we keep updating the list which is an ItemsSource. I tested with keyword "One Piece" which produced a big list. 

Should I make temporary list and then 
 `MALSearchResults.Clear(); MALSearchResults.Concat(tempList).toList();`?

 I am not sure if it is not the same thing internally thus will not actually change anything regarding the race condition.

**Comment by ElementalCrisis** [comment] 2016-06-24 21:59
I'm also not able to reproduce, did a search with single letters and had giant lists with no problems. Going to close this.

**Closed by ElementalCrisis** 2016-06-24 21:59 UTC
Labels: Bug - High Priority
